jobs:
  include:
    - stage: check_pep8
      language: python
      python: 3.10
      before_install:
        - python -m pip install --upgrade pip
      install:
        - pip install -r requirements.txt

      script:
        - flake8 main.py || exit 1