name: YRRPO lab 5

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Python version
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install pip
          pip install -r requirements.txt
      - name: Flake8 lint
        run: |
          flake8 main.py